default: &default
  adapter: postgresql
  pool: 5
  encoding: unicode

development:
  <<: *default
  database: insta

test:
  <<: *default
  database: insta_test

production:
  <<: *default
  database: insta_prod
